USE [master]
GO

/****** Object:  Database [FLovers]    Script Date: 2020/04/15 16:48:28 ******/
CREATE DATABASE [FLovers]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'FLovers', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\FLovers.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'FLovers_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\FLovers_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FLovers].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [FLovers] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [FLovers] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [FLovers] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [FLovers] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [FLovers] SET ARITHABORT OFF 
GO

ALTER DATABASE [FLovers] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [FLovers] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [FLovers] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [FLovers] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [FLovers] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [FLovers] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [FLovers] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [FLovers] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [FLovers] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [FLovers] SET  DISABLE_BROKER 
GO

ALTER DATABASE [FLovers] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [FLovers] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [FLovers] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [FLovers] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [FLovers] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [FLovers] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [FLovers] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [FLovers] SET RECOVERY FULL 
GO

ALTER DATABASE [FLovers] SET  MULTI_USER 
GO

ALTER DATABASE [FLovers] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [FLovers] SET DB_CHAINING OFF 
GO

ALTER DATABASE [FLovers] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [FLovers] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [FLovers] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [FLovers] SET QUERY_STORE = OFF
GO

ALTER DATABASE [FLovers] SET  READ_WRITE 
GO


